dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -y libfftw3-dev
  - cd driver_functions_ChannelExtraction 
script:
  # Run your build commands next
  - make -f channel_extraction_tool.make
  
